"""initial migration setup

Revision ID: 00a5ac24b7a4
Revises:
Create Date: 2026-06-25 00:13:27.234508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '00a5ac24b7a4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('assigned_to_user_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('date_assigned', sa.DateTime(), nullable=True),
    sa.Column('date_completed', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('barangays',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('bounds_coords', sa.JSON(), nullable=False),
    sa.Column('barangay_id', sa.Integer(), nullable=False),
    sa.Column('report_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_themes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('barangay_id')
    )
    op.create_index(op.f('ix_barangays_name'), 'barangays', ['name'], unique=True)
    op.create_table('reports',
    sa.Column('type', sa.Enum('DRAINAGE_BLOCKAGE', 'E_WASTE', 'HAZARDOUS_WASTE', 'ORGANIC_WASTE', 'PLASTIC_WASTE', 'BULKY_WASTE', 'MIXED_WASTE', 'OVERFLOWING_BIN_S', 'ILLEGAL_DUMPING', name='reporttype'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('report_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report_themes', sa.JSON(), nullable=True),
    sa.Column('reported_by_user_id', sa.Integer(), nullable=False),
    sa.Column('under_barangay_id', sa.Integer(), nullable=False),
    sa.Column('is_collected', sa.Boolean(), nullable=False),
    sa.Column('date_reported', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('routes',
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('waypoints', sa.JSON(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('collection_rate', sa.Float(), nullable=True),
    sa.Column('for_barangay_id', sa.Integer(), nullable=True),
    sa.Column('est_fuel_cost', sa.Float(), nullable=True),
    sa.Column('date_approved', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('route_id')
    )
    op.create_table('summary',
    sa.Column('summary_id', sa.Integer(), nullable=False),
    sa.Column('general_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('general_themes', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('role', sa.Enum('CITIZEN', 'ADMIN', 'COLLECTOR', name='role'), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('reject_tokens_before_timestamp', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('summary')
    op.drop_table('routes')
    op.drop_table('reports')
    op.drop_index(op.f('ix_barangays_name'), table_name='barangays')
    op.drop_table('barangays')
    op.drop_table('assignments')
    # ### end Alembic commands ###
