"""add notifications table

Revision ID: 0f28f6293891
Revises: d916f53ec7d9
Create Date: 2026-06-27 00:03:41.917464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f28f6293891'
down_revision: Union[str, Sequence[str], None] = 'd916f53ec7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('assignments', sa.Column('is_tracked_by_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'is_tracked_by_admin')
    op.drop_column('assignments', 'deadline')
    # ### end Alembic commands ###
