"""add date_created column to assignments table

Revision ID: 5da03a6ac773
Revises: cec2a5d2e745
Create Date: 2026-06-27 01:46:58.915913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5da03a6ac773'
down_revision: Union[str, Sequence[str], None] = 'cec2a5d2e745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('collection_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'collection_date')
    # ### end Alembic commands ###
