"""add additional column for assignments table

Revision ID: cec2a5d2e745
Revises: 0f28f6293891
Create Date: 2026-06-27 00:39:32.299810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'cec2a5d2e745'
down_revision: Union[str, Sequence[str], None] = '0f28f6293891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('current_truck_latlong', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignments', 'current_truck_latlong')
    # ### end Alembic commands ###
